### ISSUE TITLE
ArgumentNullException on GetDotProduct

### ISSUE THREAD

**Issue by cburtin** [skotz/cp-user-behavior#1]
I'm not a specialist, so maybe I'm wrong, but for every "real stuff" I'm trying to train (format of UserBehaviour is respected), a ArgumentNullException is thrown on GeDotProduct (second argument is null).
Here is my test file (data has been anonymized but comes from "real world" example)
[TestUserBehaviour.txt](https://github.com/skotz/cp-user-behavior/files/2040233/TestUserBehaviour.txt)

Thanks a lot for this work.

**Comment by skotz** [comment]
Figured it out! I was incorrectly initializing the item feature array to the count of users instead of items. Since my tests happened to have the same number of users as items, I never found this bug. If you get the latest from the master branch and try again, it should work.

**Comment by cburtin** [comment]
Thank you, the program seems to work. I will check and analyze the results soon to provide you a more accurate feedback.
